name: casemet
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  file_picker: 
  firebase_storage: 
  curved_navigation_bar: 
  flutter_rating_bar: 
  flutter_social_button:
  font_awesome_flutter: 
  dio: 
  fluttertoast: 
  intl: 
  url_launcher:
  # flutter_webrtc: 
  device_preview: 
  firebase_core: 
  firebase_auth:
  cloud_firestore: 
  flutter_local_notifications: 
  shared_preferences: 
  provider:
  google_sign_in:
  # firebase_data_connector:
  # razorpay_flutter: ^1.3.7

  
  image_picker: 
  image_cropper: 
  uuid: 
  flutter_lints: 
  # image_picker: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/signin.png
    - assets/images/
    - assets/lawyer/
    - assets/services/
    - assets/profile/
    - assets/json/
